import * as dotenv from "dotenv";
dotenv.config();

const {
  URI,
  PORT,
  SECRET_REFRESH_TOKEN,
  SECRET_ACCESS_TOKEN,
  WHITE_LISTED_END_POINTS,
  TTL,
  REDIS_HOST,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET
} = process.env;

export {
  URI,
  PORT,
  SECRET_REFRESH_TOKEN,
  SECRET_ACCESS_TOKEN,
  WHITE_LISTED_END_POINTS,
  TTL,
  REDIS_HOST,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET
};
